options:
  database:
    dbname: sead_staging_development
  log_folder: ./logs
  transfer_format: xml
  ignore_columns:
    - "date_updated"
    - "*_uuid"
policies:
  add_default_foreign_key_policy:
    tbl_dataset_contacts:
      fk_name: contact_type_id
      fk_value: 2
  if_lookup_table_is_missing_add_table_using_system_id_as_public_id:
    - tbl_abundance_elements
    - tbl_contact_types
    - tbl_dataset_submission_types
    - tbl_location_types
    - tbl_project_types
    - tbl_project_stages
    - tbl_relative_ages
    - tbl_sample_group_sampling_contexts
    - tbl_sample_types
