options:
  database:
    dbname: sead_staging_development_adna
  transfer_format: xml
  ignore_columns:
    - "date_updated"
    - "*_uuid"
policies:
  if_foreign_key_value_is_missing_add_identity_mapping_to_foreign_key_table:
    priotity: 1
  set_public_id_to_negative_system_id_for_new_lookups:
    disabled: true
  add_default_foreign_key_policy:
    tbl_dataset_contacts:
      fk_name: contact_type_id
      fk_value: 2
  if_lookup_table_is_missing_add_table_using_system_id_as_public_id:
    tables:
      - tbl_abundance_elements
      - tbl_contact_types
      - tbl_dataset_submission_types
      - tbl_location_types
      - tbl_project_types
      - tbl_project_stages
      - tbl_relative_ages
      - tbl_sample_group_sampling_contexts
      - tbl_sample_types
  if_lookup_with_no_new_data_then_keep_only_system_id_public_id:
    priority: 9
  drop_ignored_columns:
    priority: 3
    columns:
      - "date_updated"
      - "*_uuid"
logging:
  folder: ./logs
  handlers:
    - sink: "import_excel.log"
      level: "DEBUG"
      format: "{time} - {level} - {message}"
    - sink: "sys.stdout"
      level: "DEBUG"
      format: "{time} - {level} - {message}"
