with table_name_override(table_name, excel_sheet) as(values 
        ('tbl_analysis_entity_prep_methods', 'tbl_a_e_prep_method'),
        ('tbl_sample_group_description_types', 'tbl_s_g_description_types'),
        ('tbl_sample_group_description_type_sampling_contexts', 'tbl_s_g_d_t_sampling_contexts'),
        ('tbl_sample_group_sampling_contexts', 'tbl_s_g_sampling_contexts'),
        ('tbl_sample_location_type_sampling_contexts', 'tbl_s_l_t_sampling_contexts')
    ), 
    sead_table_types(table_name, table_type) as (values
        ('tbl_abundance_elements', 'lookup'),
        ('tbl_abundance_ident_levels', 'data'),
        ('tbl_abundance_modifications', 'data'),
        ('tbl_abundances', 'data'),
        ('tbl_activity_types', 'lookup'),
        ('tbl_age_types', 'lookup'),
        ('tbl_aggregate_datasets', 'unknown'),
        ('tbl_aggregate_order_types', 'lookup'),
        ('tbl_aggregate_sample_ages', 'unknown'),
        ('tbl_aggregate_samples', 'data'),
        ('tbl_alt_ref_types', 'lookup'),
        ('tbl_analysis_entities', 'data'),
        ('tbl_analysis_entity_ages', 'data'),
        ('tbl_analysis_entity_dimensions', 'data'),
        ('tbl_analysis_entity_prep_methods', 'data'), 
        ('tbl_biblio', 'metadata'),
        ('tbl_ceramics', 'data'),
        ('tbl_ceramics_lookup', 'lookup'),
        ('tbl_ceramics_measurements', 'deprecated'),
        ('tbl_chron_control_types', 'deprecated'),
        ('tbl_chron_controls', 'deprecated'),
        ('tbl_chronologies', 'data'),
        ('tbl_colours', 'lookup'),
        ('tbl_contact_types', 'lookup'),
        ('tbl_contacts', 'metadata'),
        ('tbl_coordinate_method_dimensions', 'metadata'),
        ('tbl_data_type_groups', 'lookup'),
        ('tbl_data_types', 'lookup'),
        ('tbl_dataset_contacts', 'data'),
        ('tbl_dataset_masters', 'data'),
        ('tbl_dataset_methods', 'data'),
        ('tbl_dataset_submission_types', 'lookup'),
        ('tbl_dataset_submissions', 'data'),
        ('tbl_datasets', 'data'),
        ('tbl_dating_labs', 'metadata'),
        ('tbl_dating_material', 'data'),
        ('tbl_dating_uncertainty', 'lookup'),
        ('tbl_dendro', 'data'),
        ('tbl_dendro_date_notes', 'data'),
        ('tbl_dendro_dates', 'data'),
        ('tbl_dendro_lookup', 'lookup'),
        ('tbl_dendro_measurements', 'deprecated'),
        ('tbl_dimensions', 'lookup'),
        ('tbl_ecocode_definitions', 'data'),
        ('tbl_ecocode_groups', 'data'),
        ('tbl_ecocode_systems', 'data'),
        ('tbl_ecocodes', 'data'),
        ('tbl_error_uncertainties', 'deprecated'),
        ('tbl_feature_types', 'lookup'),
        ('tbl_features', 'data'),
        ('tbl_geochron_refs', 'data'),
        ('tbl_geochronology', 'data'),
        ('tbl_horizons', 'lookup'),
        ('tbl_identification_levels', 'lookup'),
        ('tbl_image_types', 'lookup'),
        ('tbl_imported_taxa_replacements', 'unknown'),
        ('tbl_isotope_measurements', 'data'),
        ('tbl_isotope_standards', 'lookup'),
        ('tbl_isotope_types', 'lookup'),
        ('tbl_isotope_value_specifiers', 'lookup'),
        ('tbl_isotopes', 'data'),
        ('tbl_languages', 'lookup'),
        ('tbl_lithology', 'lookup'),
        ('tbl_location_types', 'lookup'),
        ('tbl_locations', 'metadata'),
        ('tbl_mcr_names', 'data'),
        ('tbl_mcr_summary_data', 'data'),
        ('tbl_mcrdata_birmbeetledat', 'data'),
        ('tbl_measured_value_dimensions', 'data'),
        ('tbl_measured_values', 'data'),
        ('tbl_method_groups', 'metadata'),
        ('tbl_methods', 'metadata'),
        ('tbl_modification_types', 'lookup'),
        ('tbl_physical_sample_features', 'data'),
        ('tbl_physical_samples', 'data'),
        ('tbl_project_stages', 'metadata'),
        ('tbl_project_types', 'lookup'),
        ('tbl_projects', 'data'),
        ('tbl_rdb', 'metadata'),
        ('tbl_rdb_codes', 'metadata'),
        ('tbl_rdb_systems', 'metadata'),
        ('tbl_record_types', 'lookup'),
        ('tbl_relative_age_refs', 'metadata'),
        ('tbl_relative_age_types', 'lookup'),
        ('tbl_relative_ages', 'lookup'),
        ('tbl_relative_dates', 'data'),
        ('tbl_sample_alt_refs', 'data'),
        ('tbl_sample_colours', 'data'),
        ('tbl_sample_coordinates', 'data'),
        ('tbl_sample_description_sample_group_contexts', 'unknown'),
        ('tbl_sample_description_types', 'lookup'),
        ('tbl_sample_descriptions', 'data'),
        ('tbl_sample_dimensions', 'data'),
        ('tbl_sample_group_coordinates', 'data'),
        ('tbl_sample_group_description_type_sampling_contexts', 'unknown'),
        ('tbl_sample_group_description_types', 'lookup'),
        ('tbl_sample_group_descriptions', 'data'),
        ('tbl_sample_group_dimensions', 'data'),
        ('tbl_sample_group_images', 'data'),
        ('tbl_sample_group_notes', 'data'),
        ('tbl_sample_group_references', 'data'),
        ('tbl_sample_group_sampling_contexts', 'unknown'),
        ('tbl_sample_groups', 'data'),
        ('tbl_sample_horizons', 'data'),
        ('tbl_sample_images', 'data'),
        ('tbl_sample_location_type_sampling_contexts', 'unknown'),
        ('tbl_sample_location_types', 'lookup'),
        ('tbl_sample_locations', 'data'),
        ('tbl_sample_notes', 'data'),
        ('tbl_sample_types', 'lookup'),
        ('tbl_season_or_qualifier', 'deprecated'),
        ('tbl_season_types', 'lookup'),
        ('tbl_seasons', 'lookup'),
        ('tbl_site_images', 'data'),
        ('tbl_site_locations', 'data'),
        ('tbl_site_natgridrefs', 'data'),
        ('tbl_site_other_records', 'data'),
        ('tbl_site_preservation_status', 'lookup'),
        ('tbl_site_references', 'data'),
        ('tbl_sites', 'data'),
        ('tbl_species_association_types', 'lookup'),
        ('tbl_species_associations', 'metadata'),
        ('tbl_taxa_common_names', 'metadata'),
        ('tbl_taxa_images', 'metadata'),
        ('tbl_taxa_measured_attributes', 'metadata'),
        ('tbl_taxa_reference_specimens', 'metadata'),
        ('tbl_taxa_seasonality', 'metadata'),
        ('tbl_taxa_synonyms', 'metadata'),
        ('tbl_taxa_tree_authors', 'metadata'),
        ('tbl_taxa_tree_families', 'metadata'),
        ('tbl_taxa_tree_genera', 'metadata'),
        ('tbl_taxa_tree_master', 'metadata'),
        ('tbl_taxa_tree_orders', 'metadata'),
        ('tbl_taxonomic_order', 'metadata'),
        ('tbl_taxonomic_order_biblio', 'metadata'),
        ('tbl_taxonomic_order_systems', 'metadata'),
        ('tbl_taxonomy_notes', 'metadata'),
        ('tbl_temperatures', 'metadata'),
        ('tbl_tephra_dates', 'deprecated'),
        ('tbl_tephra_refs', 'deprecated'),
        ('tbl_tephras', 'deprecated'),
        ('tbl_text_biology', 'metadata'),
        ('tbl_text_distribution', 'metadata'),
        ('tbl_text_identification_keys', 'metadata'),
        ('tbl_units', 'lookup'),
        ('tbl_updates_log', 'other'),
        ('tbl_years_types', 'lookup')
    ),
    import_tables as (
        select 
            t.table_name,
            t.column_name as pk_name,
            replace(initcap(table_name), '_', '') as java_class,
            coalesce(o.excel_sheet, t.table_name) as excel_sheet,
            case when coalesce(tt.table_type, 'unknown') in ('lookup', 'metadata') then true else false end as is_lookup_table
        from sead_utility.table_columns t
        left join table_name_override o using (table_name)
        left join sead_table_types tt using (table_name)
        where t.table_schema = 'public'
          and is_pk = 'YES'
)  select *
   from import_tables
