options:
  database:
    host: DBHOST
    dbname: DBNAME
    user: DBUSER
    port: DBPORT
  transfer_format: xml
  ignore_columns:
    - "date_updated"
    - "*_uuid"
    - "(*"
policies:
  if_foreign_key_value_is_missing_add_identity_mapping_to_foreign_key_table:
    priority: 1
  set_public_id_to_negative_system_id_for_new_lookups:
    disabled: true
  update_missing_foreign_key_policy:
    tbl_dataset_contacts:
      contact_type_id: 2
      contact_id: 1
  if_lookup_table_is_missing_add_table_using_system_id_as_public_id:
    tables:
      - tbl_abundance_elements
      - tbl_contact_types
      - tbl_dataset_submission_types
      - tbl_location_types
      - tbl_project_types
      - tbl_project_stages
      - tbl_relative_ages
      - tbl_sample_group_sampling_contexts
      - tbl_sample_types
  if_lookup_with_no_new_data_then_keep_only_system_id_public_id:
    priority: 9
  drop_ignored_columns:
    priority: 3
    columns:
      - "date_updated"
      - "*_uuid"
logging:
  folder: ./logs
  handlers:
    - sink: "import_excel.log"
      level: "DEBUG"
      format: "{time} - {level} - {message}"
    - sink: "sys.stdout"
      level: "WARNING"
      format: "{time} - {level} - {message}"
test:
  sites:
    - 1635
  reduced_excel_filename: tests/test_data/building_dendro_reduced.xlsx
  source_excel_filename: data/input/building_dendro_2023-12_import.xlsx
  tables:
    - tbl_abundances
    - tbl_analysis_entities
    - tbl_dataset_contacts
    - tbl_dataset_submissions
    - tbl_datasets
    - tbl_dendro_date_notes
    - tbl_dendro_dates
    - tbl_dendro
    - tbl_locations
    - tbl_methods
    - tbl_physical_samples
    - tbl_projects
    - tbl_record_types
    - tbl_sample_alt_refs
    - tbl_sample_descriptions
    - tbl_sample_group_coordinates
    - tbl_sample_group_descriptions
    - tbl_sample_group_notes
    - tbl_sample_group_sampling_contexts
    - tbl_sample_groups
    - tbl_sample_locations
    - tbl_sample_notes
    - tbl_site_locations
    - tbl_site_references
    - tbl_site

  adna:
    source:
      filename: data/input/SEAD_aDNA_data_20241114_RM.xlsx
